version: '3.6'

services:
  victim_lfi_server_asp:
        container_name: "victim.lfi.asp.tld"
        build: ./victim_lfi_server_asp
        ports:
        - "8080:5002"
        environment:
        - SERVER_HOST_EXTERNAL_IP=${DOCKER_VM_IP}
        - SERVER_HOST_EXTERNAL_PORT=8080
  attacker_server_win:
        container_name: "attacker.lfi.win.tld"
        build: ./attacker_server_win
        ports:
        - "8081:5002"
        environment:
        - SERVER_HOST_EXTERNAL_IP=${DOCKER_VM_IP}
        - SERVER_HOST_EXTERNAL_PORT=8081
 

networks:
  default:
    external:
      name: nat          
